title: Matthew Johnston
subtitle: Professional Code Janitor
url: http://www.mattjohnston.co
simple_search: http://google.com/search
email: warmwaffles@gmail.com

# Site settings
description: > # this means to ignore newlines until "baseurl:"
  My adventures through code and time. Ranging from C, Ruby, Java, and the
  occassional DIY projects.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: warmwaffle
github_username:  warmwaffles

# Build settings
markdown: kramdown

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-paginate
  - rouge
  - redcarpet
  - uglifier

include:
  - .htaccess
  - keybase.txt

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Mercfile
  - lib
  - .bowerrc
  - bower.json
  - package.json
  - TODO
  - node_modules
  - bower_modules

# Conversion
markdown: redcarpet
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"

# Pagination
paginate_path: /blog/page/:num
paginate: 5

# Outputting
permalink: /blog/:year/:month/:day/:title
date_format: ordinal
timezone: null
quiet:    false
defaults: []

# Markdown Processors
redcarpet:
  extensions:
    - fenced_code_blocks
    - tables
    - autolink

# Deployment Settings
rsync:
  user: warmwaffles
  host: mattjohnston.co
  root: /var/www/www.mattjohnston.co

# Plugin: jekyll-assets
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: hard
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false

# Plugin: jekyll-sitemap
sitemap: true

google_analytics:
  tracking_id: UA-28154723-1

gravatar:
  hash: 194f2c377bafdebb453e07413ca9294f
  size: 240
