# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matthew Johnston
email: warmwaffles@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My adventures through code and time. Ranging from C, Ruby, Java, and the
  occassional DIY projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.mattjohnston.co" # the base hostname & protocol for your site
twitter_username: warmwaffle
github_username:  warmwaffles

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-paginate
  - rouge
  - redcarpet
  - uglifier

include:
  - .htaccess
  - keybase.txt

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Mercfile
  - lib
  - .bowerrc
  - bower.json
  - package.json
  - TODO
  - node_modules
  - bower_modules

# Conversion
markdown: redcarpet
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"

include:
  - .htaccess
  - keybase.txt

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Mercfile
  - lib
  - .bowerrc
  - bower.json
  - package.json
  - TODO
  - node_modules
  - bower_modules

# Plugin: jekyll-assets
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: hard
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false

# Plugin: jekyll-sitemap
sitemap: true

# Pagination
paginate_path: /blog/page/:num
paginate: 5

# Outputting
permalink: /blog/:year/:month/:day/:title
date_format: ordinal
timezone: null
quiet:    false
defaults: []

google_analytics:
  tracking_id: UA-28154723-1

gravatar:
  hash: 194f2c377bafdebb453e07413ca9294f
  size: 240
