# Site settings
title: Matthew Johnston
email: warmwaffles@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My adventures through code and time. Ranging from C, Ruby, Java, and the
  occassional DIY projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.mattjohnston.co" # the base hostname & protocol for your site
twitter_username: warmwaffle
github_username:  warmwaffles

# Where things are
source: .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes

# Handling Reading
safe: false
include:
  - .htaccess
  - keybase.txt
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - TODO
  - tmp
keep_files: []
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-paginate
  - rouge
  - kramdown
  - uglifier

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname
show_dir_listing: false

# Outputting
permalink: /posts/:year/:month/:day/:title
paginate_path: /posts/page/:num
paginate: 5
timezone: null

quiet:    false
verbose:  false

collections:
  posts:
    output: true
  projects:
    output: true
    permalink: /projects/:path/
    index: projects.html
defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"


liquid:
  error_mode: warn

sass:
  style: compressed

# Markdown Processors
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

# Plugin: jekyll-sitemap
sitemap: true

# Plugin: jekyll-assets
assets:
  dirname: assets
  baseurl: /assets/
  digest: true
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: hard
  cache: false
  debug: false
  features:
    liquid: true
