# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Matthew Johnston
email: warmwaffles@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My adventures through code and time. Ranging from C, Ruby, Java, and the
  occassional DIY projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.mattjohnston.co" # the base hostname & protocol for your site
twitter_username: warmwaffle
github_username:  warmwaffles

# Build settings
markdown: kramdown
theme: pixyll
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-paginate

# Handling Reading
safe: false
include:
  - .htaccess
  - keybase.txt
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Rakefile
  - TODO
  - tmp
keep_files: []
encoding: "utf-8"
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugin: jekyll-sitemap
sitemap: true

# Plugin: jekyll-assets
assets:
  destination: "/assets"

# Markdown Processors
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

permalink: /posts/:year/:month/:day/:title.html
paginate_path: /posts/page/:num
paginate: 5
timezone: null

collections:
  posts:
    output: true
  projects:
    output: true
    permalink: /projects/:path/
    index: projects.html
defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
